#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015 SeukWon Kang (kasworld@gmail.com)
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# generated by wxGlade 0.6.3 on Sat Nov 21 10:56:41 2009

import wx
import sys
import os.path
import time
import math
from time import strftime, localtime

# begin wxGlade: extracode
# end wxGlade


class wxStopWatch(wx.Frame):

    def __init__(self, *args, **kwds):
        # begin wxGlade: wxStopWatch.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_stopwatch = wx.StaticText(
            self, -1, "00:00:00", style=wx.ALIGN_CENTRE)
        self.button_startstop = wx.Button(self, -1, "&Start")
        self.button_lap = wx.Button(self, -1, "C&lear")
        self.list_lap = wx.ListCtrl(
            self, -1, style=wx.LC_REPORT | wx.LC_NO_HEADER | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.evt_startstop, self.button_startstop)
        self.Bind(wx.EVT_BUTTON, self.evt_lap, self.button_lap)
        # end wxGlade
        self.Bind(wx.EVT_TIMER, self._OnTimer)
        self.timer = wx.Timer(self)
        self.timerstarted = False
        self.list_lap.InsertColumn(
            0, '', format=wx.LIST_FORMAT_LEFT, width=220)
        self.Bind(wx.EVT_SIZE, self._OnSize)

    def _OnSize(self, evt):
        # print "_OnSize"
        size = self.GetClientSize()
        if size.x < 1 or size.y < 1:
            return
        fp = max(min(size.y / 3, size.x / 6), 6)
        self.label_stopwatch.SetFont(
            wx.Font(fp, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.Layout()

    def __set_properties(self):
        # begin wxGlade: wxStopWatch.__set_properties
        self.SetTitle("WxStopWatch")
        self.SetSize((640, 480))
        self.label_stopwatch.SetFont(
            wx.Font(48, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_startstop.SetFont(
            wx.Font(48, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_startstop.SetFocus()
        self.button_lap.SetFont(
            wx.Font(48, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.list_lap.SetFont(
            wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxStopWatch.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.label_stopwatch, 1,
                    wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(
            sizer_3, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.button_startstop, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_lap, 1, wx.EXPAND, 0)
        sizer_2.Add(self.list_lap, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def evt_startstop(self, event):  # wxGlade: wxStopWatch.<event_handler>
        if self.timerstarted == False:
            self.timerstarted = True
            self.starttime = time.time()
            self.button_startstop.SetLabel('&Stop')
            self.button_lap.SetLabel('&Lap')
            self.Update()
            self.timer.Start(10)
        else:
            self.timer.Stop()
            self.timerstarted = False
            self.button_startstop.SetLabel('&Start')
            self.button_lap.SetLabel('C&lear')

    def evt_lap(self, event):  # wxGlade: wxStopWatch.<event_handler>
        if self.timerstarted == False:
            # clear
            self.label_stopwatch.SetLabel('00:00:00')
            self.list_lap.ClearAll()
            self.list_lap.InsertColumn(
                0, '', format=wx.LIST_FORMAT_LEFT, width=220)
        else:
            # lap
            toprint = time.time() - self.starttime
            printstr = "%02d:%02d:%02d" % (
                int(toprint) / 60, int(toprint) % 60, (toprint - int(toprint)) * 100)
            self.list_lap.InsertStringItem(0, printstr)
            # self.Refresh(False)
            # self.Update()
            # self.list_lap.UpdateWindowUI()

    def _OnTimer(self, evt):
        toprint = time.time() - self.starttime
        printstr = "%02d:%02d:%02d" % (
            int(toprint) / 60, int(toprint) % 60, (toprint - int(toprint)) * 100)
        self.label_stopwatch.SetLabel(printstr)
        # self.Refresh(False)
        self.Update()

# end of class wxStopWatch


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = wxStopWatch(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
